theme: jekyll-theme-cayman
title: Boaz Rensenbrink
description: A Scrum Master who is keen to offer ten years of relevant experience and pursues new professional challenges.
google_analytics: UA-150421771-1
show_personal_links: true
